name: Go Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    # Go uses the toolchain version in go.mod since 1.21
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.6' 

    - name: Unit Test
      run: go test -v -race ./...
